### PR TITLE
Adding of Backslash escape support, number of day, name of day, name of month and Browser support.

### PR DESCRIPTION
**Pull request by Haeresis**
Hi nomiddlename,

For my own development I have modify your great code and if you want, you could merged or implement part of my code or all.

New features are
- Number of day, name of day, name of month: 
  for example `DDDD dd MMMM yyyy`
  `//=> Monday 10 January 2010`
  or
  `//=> Lundi 10 Janvier 2010`
  etc. depend of array passed in parameter.
- Backslash escape support
  Allow you to write « Votre co\mmande arrivera le dd/MM/yyyy » : 
  `//=> Votre commande arrivera le 10/11/2017` and not `//=> Votre co47ande arrivera le 10/11/2017`
- Browser support
  I scope `exports` into a if test for use your script into browser with `website.utils.dateFormat`

Read the README.md or/and lib/index.js for see more.

Thx !

### CODE REVIEW

**Comment by nomiddlename** [comment]
Hi, thanks for this. It looks like this PR removes the LICENCE and package.json files. That's not good :) Also, there are no tests to cover the new features.

**Comment by Haeresis** [comment]
Oh, I didn't think you cannot accept a partial code of a PR, and keep your Package and your Licence. I will add back Package and Licence. For Tests, you're right! I will add some Tests !

**Comment by Haeresis** [comment]
It's done ! I added some Tests and I add back LICENCE and packaqe.json. 

I have add « contributors » into package.json with my entry. It's a good thing to add others contributors :). 

I have rename index.js from lib into date-format.js for use into browser. package.json have `lib/date-format.js` in main for npm install. In `date-format_test.js`, I change `require('../lib/index')` into `require('../')` because if you rename `date-format.js` into `index.js` or `other-name.js` the code will run if you change `main` property into `package.json`.

**Comment by Haeresis** [comment]
I change order of replacement for avoid this sort of problem : « October » becomo « +200ctober ».

**Pull request closed without merging**
