### PR TITLE
Fixes timezone format

### LINKED ISSUE #24: Colon in timezone
According to https://en.wikipedia.org/wiki/ISO_8601 the timezone is recommended to contain a colon.

> Representations can be done in one of two formats – a basic format with a minimal number of separators or an extended format with separators added to enhance human readability.[14][15] The standard notes that "The basic format should be avoided in plain text."[16] The separator used between date values (year, month, week, and day) is the hyphen, while the colon is used as the separator between time values (hours, minutes, and seconds). For example, the 6th day of the 1st month of the year 2009 may be written as "2009-01-06" in the extended format or simply as "20090106" in the basic format without ambiguity.

RFC3339, that is a profile of ISO 8601, also states that the offset between local time and UTC is defined as:

> time-numoffset  = ("+" / "-") time-hour ":" time-minute

As such, should the the O format string should most likely include a colon, right?

### PR DESCRIPTION
**Pull request by peteriman**
Fixes #24

### CODE REVIEW

**Comment by nomiddlename** [comment]
I would have thought that this would break a few existing tests?

**Comment by peteriman** [comment]
You are right, I have corrected and pushed in those tests.

**Comment by thernstig** [comment]
@peteriman Include this in a new log4js update :)?

**Comment by peteriman** [comment]
@thernstig Not yet. It will be in the upcoming `log4js` update, either `6.4.0` or `7.0.0`.

**Comment by peteriman** [comment]
@thernstig It is released in `log4js@6.4.0`.

**Pull request merged**
